# Generated by Django 3.2.13 on 2022-04-24 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_candidate', models.BooleanField(default=False)),
                ('is_interviewer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slot', models.IntegerField(choices=[(1, '10AM-11AM'), (2, '11AM-12PM'), (3, '12PM-1PM'), (4, '1PM-2PM'), (5, '2PM-3PM'), (6, '3PM-4PM'), (7, '4PM-5PM'), (8, '5PM-6PM')], default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.user')),
            ],
        ),
    ]
